version: '3.8'

services:
  app:
    build:
      context: .  # Контекст збірки: поточна директорія
      dockerfile: Dockerfile  # Шлях до вашого Dockerfile
    ports:
      - "3000:3000"  # Проксіє порт з контейнера на хост-машину
    volumes:
      - .:/app  # Мапить поточну директорію на контейнер, для автоматичного оновлення під час розробки
    environment:
      NODE_ENV: development  # Оточення для додатка
      MONGODB_URI: "mongodb+srv://olegvtorenko:uLQv5KYVoWHCfwSM@cluster0.ws6iz.mongodb.net/"  # Ваш MongoDB URI
    depends_on:
      - db  # Якщо є залежність від бази даних

  db:
    image: mongo:latest  # Використовуємо останній офіційний образ MongoDB
    ports:
      - "27017:27017"  # Проксіє порт MongoDB на хост
    volumes:
      - db_data:/data/db  # Зберігання даних MongoDB між перезавантаженнями контейнера

volumes:
  db_data:  # Оголошуємо том для зберігання даних MongoDB
